version: '3.7'

services:
  myapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapi
    ports:
      - "5000:80"
    environment:
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
    networks:
      - elk_default

networks:
  elk_default:
    external: true
