version: '3.7'

services:
  python-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_api
    ports:
      - "8000:8000"
    environment:
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
    networks:
      - elk_default

networks:
  elk_default:
    external: true
