version: '3.7'

services:
  nodejs-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_api
    ports:
      - "3000:3000"
    environment:
      - LOGSTASH_HOST=logstash
      - LOGSTASH_PORT=5044
    networks:
      - elk_default

networks:
  elk_default:
    external: true
